apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: typesense
  labels:
    service: typesense
    app: typesense
spec:
  serviceName: ts
  podManagementPolicy: Parallel
  # NOTE: This is number of nodes that we want to run
  # you may update this
  replicas: 1
  selector:
    matchLabels:
      service: typesense
      app: typesense
  template:
    metadata:
      labels:
        service: typesense
        app: typesense
    spec:
      securityContext:
        fsGroup: 2000
        runAsUser: 10000
        runAsGroup: 3000
        runAsNonRoot: true
      terminationGracePeriodSeconds: 300
      containers:
        - name: typesense
          # NOTE : you can update to the latest release
          image: us-east4-docker.pkg.dev/backlinks-81c44/typesense/typesense:0.23.1
          # command:
          #   - "/opt/typesense-server"
          #   - "-d"
          #   - "/usr/share/typesense/data"
          #   - "-a"
          #   - "abcxyz"
          #   - "--api-port"
          #   - "8108"
          #   - "--peering-port"
          #   - "8107"
          #   - "--nodes"
          #   - "/usr/share/typesense/nodes"

          # Load config values as environment variables.
          envFrom:
            - configMapRef:
                name: typesense
          ports:
            - containerPort: 8108
              name: http
          # NOTE: you can increase these resources
          # resources:
          #   requests:
          #     memory: 100Mi
          #     cpu: "64m"
          #   limits:
          #     memory: 256Mi
          #     cpu: "512m"
          volumeMounts:
            - name: data
              mountPath: /usr/share/typesense/data

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        # NOTE: Make sure to update your storageClass depending on your provider
        # storageClassName: default
        # NOTE: You can increase the storage size
        resources:
          requests:
            storage: 10Gi
