version: "3"
services:
  typesense:
    image: typesense/typesense:0.23.1
    environment:
      TYPESENSE_API_KEY: abcxyz
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_ENABLE_CORS: "true"
    ports:
      - "8108:8108"
    volumes:
      - typesense-data:/data
    networks:
      - common_network

  server:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../secrets/firebase-sa.json:/config/firebase-sa.json
    command:
      - "/app"
      - "--typesense.key=abcxyz"
      - "--firestore.projectid=backlinks-81c44"
      - "--firestore.creds=/config/firebase-sa.json"
      # - "--force.recreate=true"
      - "--skip.firestore=true"
    depends_on:
      - typesense
    networks:
      - common_network

volumes:
  typesense-data:
    driver: local

networks:
  common_network:
