version: "3"
services:
  typesense:
    image: typesense/typesense:0.23.1
    environment:
      TYPESENSE_API_KEY: abcxyz
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_ENABLE_CORS: "true"
    # entrypoint: sh -c "/opt/typesense-server --data-dir /data --api-key=abcxyz --enable-cors"
    ports:
      - "8108:8108"
    volumes:
      - typesense-data:/data
    # networks:
    #   - serverdb

  server:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./firebase-sa.json:/config/firebase-sa.json
    command:
      - "/app"
      - "--typesense.key=abcxyz"
      - "--firestore.projectid=backlinks-81c44"
      - "--firestore.creds=/config/firebase-sa.json"
    depends_on:
      - typesense
    # networks:
    #   - serverdb

volumes:
  typesense-data:
    driver: local
# networks:
#   serverdb:
#     driver: bridge
