---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ui
  labels:
    service: ui
    app: ui

spec:
  replicas: 1
  selector:
    matchLabels:
      service: ui
      app: ui
  template:
    metadata:
      labels:
        service: ui
        app: ui
    spec:
      containers:
        - image: us-east4-docker.pkg.dev/backlinks-81c44/ui/ui:20221231
          name: ui
          imagePullPolicy: Always

          env:
            - name: SERVER_URL
              value: "http://server:8000"

            - name: NEXT_PUBLIC_GOOGLE_ANALYTICS
              valueFrom:
                secretKeyRef:
                  name: ui
                  key: NEXT_PUBLIC_GOOGLE_ANALYTICS

          command: ["sh"]
          args: ["-c", "npm start"]

          resources:
            limits:
              cpu: 250m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 128Mi

          ports:
            - containerPort: 3000

          # livenessProbe:
          #   httpGet:
          #     scheme: HTTP
          #     path: /live
          #     port: 8001
          #   initialDelaySeconds: 3
          #   periodSeconds: 5

          # readinessProbe params should be used in GKE ingress health check
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /about
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 60
