version: "3"

services:
  ui:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      FIREBASE_CONFIG: $FIREBASE_CONFIG
      SERVER_URL: http://localhost:8000
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    # command: "npm start"
